# Generated by Django 5.2 on 2025-05-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.CharField(blank=True, default=0.0, max_length=255, null=True),
        ),
    ]
