# Generated by Django 5.2 on 2025-04-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category_alter_skill_category'),
        ('users', '0002_remove_freelancer_skills_freelancer_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='preferred_categories',
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='clients', to='services.category'),
        ),
    ]
