# Generated by Django 5.2 on 2025-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_freelancer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
