# Generated by Django 5.2 on 2025-04-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_client_preferred_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='languages',
        ),
    ]
