# Generated by Django 5.2 on 2025-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category_alter_skill_category'),
        ('users', '0004_remove_freelancer_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='services.category'),
        ),
    ]
