# Generated by Django 5.2 on 2025-04-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='services.category'),
        ),
    ]
